GET http://localhost:5000/api/mascotas/

###

GET http://localhost:5000/api/personal/6237630be8a6495cea600cdb

###

POST http://localhost:5000/api/mascotas/
Content-Type: application/json

{
    "tipo": "Mono",
    "raza": "Orangutan",
    "nombre": "Pedro",
    "sexo": "M",
    "estatura": 1.23,
    "ubicacion": [3.511815, -45.797119]
}

### 
DELETE http://localhost:5000/api/mascotas/623d2cc7a021479edce5ab59

###
DELETE http://localhost:5000/api/mascotas/*

### 
PATCH  http://localhost:5000/api/mascotas/623d2d25a021479edce5ab62
Content-Type: application/json

{
    "ubicacion": [5.511815,-64.797119 ]
}