GET http://localhost:5000/api/mascotas/

###

GET http://localhost:5000/api/historiales/

###

GET http://localhost:5000/api/mascotas/623fcc7073916b6d63612e36
###

GET http://localhost:5000/api/historiales/623fcc7073916b6d63612e36
###

GET http://localhost:5000/api/historiales/623fcc7073916b6d63612e36/623fcc9973916b6d63612e40
###

POST http://localhost:5000/api/mascotas/
Content-Type: application/json

{
    "tipo": "Estoy",
    "raza": "Estoy",
    "nombre": "Estoy",
    "sexo": "Estoy",
    "estatura": 6969.0,
    "ubicacion": [6.0, -69.0],
    "encontrado_por": "Drogao"
}

###

POST http://localhost:5000/api/historiales/624101c5a827210e0a421396
Content-Type: application/json

{
    "descripcion":   "Vacuna contra el covid.",
    "evento":        "Vacunacion",
    "medico":        "623f6a5531ad917490f21171"
}

### 
DELETE http://localhost:5000/api/historiales/*/*

###
DELETE http://localhost:5000/api/personal/*


### 
DELETE http://localhost:5000/api/mascotas/624101c5a827210e0a421396

###
DELETE http://localhost:5000/api/historiales/623fd10dad966e966ee66be4/623fd114ad966e966ee66be7

### 
PATCH  http://localhost:5000/api/historiales/623fcc7073916b6d63612e36/623fcc9973916b6d63612e40
Content-Type: application/json

{
    "evento": "eventualmente sadasdas."
}