GET http://localhost:5000/api/mascotas/

###

GET http://localhost:5000/api/mascotas/623fc60e80083aa4401a94b9
###

GET http://localhost:5000/api/historiales/623fc60e80083aa4401a94b9
###

GET http://localhost:5000/api/historiales/623fc60e80083aa4401a94b9/623fc67c80083aa4401a94d1
###

POST http://localhost:5000/api/mascotas/
Content-Type: application/json

{
    "tipo": "Estoy",
    "raza": "Estoy",
    "nombre": "Estoy",
    "sexo": "Estoy",
    "estatura": 6969.0,
    "ubicacion": [6.0, -69.0],
    "encontrado_por": "Drogao"
}

###

POST http://localhost:5000/api/historiales/623fc60e80083aa4401a94b9
Content-Type: application/json

{
    "descripcion":   "Vacuna contra el covid.",
    "evento":        "Vacunacion",
    "medico":        "623f6a5531ad917490f21171"
}

### 
DELETE http://localhost:5000/api/mascotas/623d2cc7a021479edce5ab59

###
DELETE http://localhost:5000/api/historiales/623fc60e80083aa4401a94b9/623fc67c80083aa4401a94d1

### 
PATCH  http://localhost:5000/api/historiales/623fc60e80083aa4401a94b9/623fc67c80083aa4401a94d1
Content-Type: application/json

{
    "evento": "eventualmente x 2."
}